// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjhbscxaeoagxakvbwfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqaGJzY3hhZW9hZ3hha3Zid2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzAwMjIsImV4cCI6MjA2Mzk0NjAyMn0.qcLB4nRi3GWZMp9m4OTFVq6P_jD5BslSRdJpaAqoSjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);